### ISSUE TITLE
Email verification is broken

### ISSUE THREAD

**Issue by eric-mh** [codeday-labs/wej-tech#17]
Email verification during sign-up is broken because it previously used a personal email that's been blocked.

**Comment by eric-mh** [comment]
This should be resolved by creating a non personal account somewhere, and attaching to this app.

**Comment by echo4eva** [comment]
**How to get this fix on your local machine**

- install a library that lets us have environment variables
 `pip install python-dotenv`

- create a file named `.env` within your project/settings folder that has `settings.py`

- within the `.env` file, write this:
email=check_slack
pass=for_email_and_pass!

After that, you just need to pull the changes that include this bug, since I will include commit/push the usage of environment variables in settings.py.
